name: TDR Deploy Graphql Client
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/sbt_release.yml@27efbc03aaaa9696eea85ab7a9363d6f92733471 # v0.0.34
    with:
      library-name: "Graphql Client"
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
