name: TDR Deploy Graphql Client
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/sbt_release.yml@f4d7086babd2c5156dd483d445e4500a603d8dc4 # v0.0.42
    with:
      library-name: "Graphql Client"
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
